# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 580)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 580))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 580))
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWhatsThis("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(20, 9, 960, 480))
        self.tabWidget.setMinimumSize(QtCore.QSize(960, 480))
        self.tabWidget.setMaximumSize(QtCore.QSize(960, 480))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_PCB = QtWidgets.QWidget()
        self.tab_PCB.setObjectName("tab_PCB")
        self.label_PcbCaseInfor = QtWidgets.QLabel(self.tab_PCB)
        self.label_PcbCaseInfor.setGeometry(QtCore.QRect(20, 220, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_PcbCaseInfor.setFont(font)
        self.label_PcbCaseInfor.setObjectName("label_PcbCaseInfor")
        self.tableWidget_PcbCaseInfor = QtWidgets.QTableWidget(self.tab_PCB)
        self.tableWidget_PcbCaseInfor.setEnabled(True)
        self.tableWidget_PcbCaseInfor.setGeometry(QtCore.QRect(20, 250, 910, 151))
        self.tableWidget_PcbCaseInfor.setAutoFillBackground(False)
        self.tableWidget_PcbCaseInfor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_PcbCaseInfor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_PcbCaseInfor.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_PcbCaseInfor.setAutoScroll(False)
        self.tableWidget_PcbCaseInfor.setCornerButtonEnabled(True)
        self.tableWidget_PcbCaseInfor.setObjectName("tableWidget_PcbCaseInfor")
        self.tableWidget_PcbCaseInfor.setColumnCount(6)
        self.tableWidget_PcbCaseInfor.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbCaseInfor.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbCaseInfor.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbCaseInfor.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbCaseInfor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbCaseInfor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbCaseInfor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbCaseInfor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbCaseInfor.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbCaseInfor.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbCaseInfor.setItem(0, 3, item)
        self.tableWidget_PcbCaseInfor.horizontalHeader().setVisible(True)
        self.tableWidget_PcbCaseInfor.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_PcbCaseInfor.horizontalHeader().setDefaultSectionSize(138)
        self.tableWidget_PcbCaseInfor.horizontalHeader().setHighlightSections(True)
        self.tableWidget_PcbCaseInfor.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_PcbCaseInfor.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_PcbCaseInfor.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_PcbCaseInfor.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget_PcbCaseInfor.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget_PcbCaseInfor.verticalHeader().setStretchLastSection(True)
        self.label_AmbientTemp = QtWidgets.QLabel(self.tab_PCB)
        self.label_AmbientTemp.setGeometry(QtCore.QRect(20, 110, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_AmbientTemp.setFont(font)
        self.label_AmbientTemp.setObjectName("label_AmbientTemp")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_PCB)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 130, 221, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_AmbientTemp = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_AmbientTemp.setObjectName("lineEdit_AmbientTemp")
        self.horizontalLayout_2.addWidget(self.lineEdit_AmbientTemp)
        self.label_AmbientTempUnit = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_AmbientTempUnit.setObjectName("label_AmbientTempUnit")
        self.horizontalLayout_2.addWidget(self.label_AmbientTempUnit)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_PCB)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 221, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_ModelName = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_ModelName.setFont(font)
        self.label_ModelName.setObjectName("label_ModelName")
        self.verticalLayout.addWidget(self.label_ModelName)
        self.lineEdit_ModelName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_ModelName.setText("")
        self.lineEdit_ModelName.setObjectName("lineEdit_ModelName")
        self.verticalLayout.addWidget(self.lineEdit_ModelName)
        self.label = QtWidgets.QLabel(self.tab_PCB)
        self.label.setGeometry(QtCore.QRect(690, 410, 251, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_PCB)
        self.label_2.setGeometry(QtCore.QRect(280, 20, 321, 211))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_PCB)
        self.label_3.setGeometry(QtCore.QRect(610, 40, 321, 161))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_PCB, "")
        self.tab_Layers = QtWidgets.QWidget()
        self.tab_Layers.setObjectName("tab_Layers")
        self.tableWidget_PcbLayers = QtWidgets.QTableWidget(self.tab_Layers)
        self.tableWidget_PcbLayers.setGeometry(QtCore.QRect(20, 50, 451, 381))
        self.tableWidget_PcbLayers.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_PcbLayers.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_PcbLayers.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_PcbLayers.setObjectName("tableWidget_PcbLayers")
        self.tableWidget_PcbLayers.setColumnCount(2)
        self.tableWidget_PcbLayers.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbLayers.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbLayers.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbLayers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PcbLayers.setHorizontalHeaderItem(1, item)
        self.tableWidget_PcbLayers.horizontalHeader().setDefaultSectionSize(165)
        self.tableWidget_PcbLayers.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_Layers)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 10, 371, 33))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_PcbLayerNumber = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(".Lucida Grande UI")
        font.setPointSize(15)
        self.label_PcbLayerNumber.setFont(font)
        self.label_PcbLayerNumber.setObjectName("label_PcbLayerNumber")
        self.horizontalLayout_5.addWidget(self.label_PcbLayerNumber)
        self.lineEdit_PcbLayerNumber = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_PcbLayerNumber.setObjectName("lineEdit_PcbLayerNumber")
        self.horizontalLayout_5.addWidget(self.lineEdit_PcbLayerNumber)
        self.pushButton_PcbLayerNumber = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_PcbLayerNumber.setObjectName("pushButton_PcbLayerNumber")
        self.horizontalLayout_5.addWidget(self.pushButton_PcbLayerNumber)
        self.Image_Stackup = QtWidgets.QLabel(self.tab_Layers)
        self.Image_Stackup.setGeometry(QtCore.QRect(500, 30, 441, 411))
        self.Image_Stackup.setObjectName("Image_Stackup")
        self.tabWidget.addTab(self.tab_Layers, "")
        self.tab_Comp = QtWidgets.QWidget()
        self.tab_Comp.setObjectName("tab_Comp")
        self.tableWidget_Components = QtWidgets.QTableWidget(self.tab_Comp)
        self.tableWidget_Components.setGeometry(QtCore.QRect(30, 80, 891, 351))
        self.tableWidget_Components.setObjectName("tableWidget_Components")
        self.tableWidget_Components.setColumnCount(13)
        self.tableWidget_Components.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Components.setHorizontalHeaderItem(12, item)
        self.tableWidget_Components.horizontalHeader().setDefaultSectionSize(65)
        self.tableWidget_Components.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_Components.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_Comp)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 10, 291, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_ComponentsNumber = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_ComponentsNumber.setFont(font)
        self.label_ComponentsNumber.setObjectName("label_ComponentsNumber")
        self.horizontalLayout_4.addWidget(self.label_ComponentsNumber)
        self.lineEdit_ComponentsNumber = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_ComponentsNumber.setObjectName("lineEdit_ComponentsNumber")
        self.horizontalLayout_4.addWidget(self.lineEdit_ComponentsNumber)
        self.label_CompoentsNumberUnit = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_CompoentsNumberUnit.setObjectName("label_CompoentsNumberUnit")
        self.horizontalLayout_4.addWidget(self.label_CompoentsNumberUnit)
        self.pushButton_ComponentsNumber = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_ComponentsNumber.setObjectName("pushButton_ComponentsNumber")
        self.horizontalLayout_4.addWidget(self.pushButton_ComponentsNumber)
        self.tabWidget.addTab(self.tab_Comp, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(600, 10, 345, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_LoadModel = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_LoadModel.setObjectName("pushButton_LoadModel")
        self.horizontalLayout_3.addWidget(self.pushButton_LoadModel)
        self.pushButton_DeleteModel = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_DeleteModel.setObjectName("pushButton_DeleteModel")
        self.horizontalLayout_3.addWidget(self.pushButton_DeleteModel)
        self.pushButton_CheckModel = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_CheckModel.setEnabled(True)
        self.pushButton_CheckModel.setObjectName("pushButton_CheckModel")
        self.horizontalLayout_3.addWidget(self.pushButton_CheckModel)
        self.comboBox_Boards = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_Boards.setGeometry(QtCore.QRect(10, 10, 571, 51))
        self.comboBox_Boards.setMaxVisibleItems(20)
        self.comboBox_Boards.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_Boards.setObjectName("comboBox_Boards")
        self.line = QtWidgets.QFrame(self.tab_4)
        self.line.setGeometry(QtCore.QRect(10, 50, 711, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_SimulationResult = QtWidgets.QLabel(self.tab_4)
        self.label_SimulationResult.setGeometry(QtCore.QRect(20, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_SimulationResult.setFont(font)
        self.label_SimulationResult.setObjectName("label_SimulationResult")
        self.tableWidget_SimulationResults = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_SimulationResults.setGeometry(QtCore.QRect(20, 110, 911, 321))
        self.tableWidget_SimulationResults.setObjectName("tableWidget_SimulationResults")
        self.tableWidget_SimulationResults.setColumnCount(9)
        self.tableWidget_SimulationResults.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SimulationResults.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SimulationResults.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SimulationResults.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SimulationResults.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SimulationResults.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SimulationResults.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SimulationResults.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SimulationResults.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SimulationResults.setHorizontalHeaderItem(8, item)
        self.tableWidget_SimulationResults.horizontalHeader().setDefaultSectionSize(96)
        self.tableWidget_SimulationResults.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(510, 500, 441, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_NewModel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_NewModel.setObjectName("pushButton_NewModel")
        self.horizontalLayout.addWidget(self.pushButton_NewModel)
        self.pushButton_SaveModel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_SaveModel.setObjectName("pushButton_SaveModel")
        self.horizontalLayout.addWidget(self.pushButton_SaveModel)
        self.pushButton_RunSimulation = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_RunSimulation.setObjectName("pushButton_RunSimulation")
        self.horizontalLayout.addWidget(self.pushButton_RunSimulation)
        self.pushButton_Exit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.horizontalLayout.addWidget(self.pushButton_Exit)
        self.progressBar_Simulation = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_Simulation.setGeometry(QtCore.QRect(70, 500, 381, 41))
        self.progressBar_Simulation.setProperty("value", 24)
        self.progressBar_Simulation.setObjectName("progressBar_Simulation")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PCB Thermal Simulator "))
        self.label_PcbCaseInfor.setText(_translate("MainWindow", "PCB & Cases Information"))
        item = self.tableWidget_PcbCaseInfor.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "PCB"))
        item = self.tableWidget_PcbCaseInfor.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Upper Case"))
        item = self.tableWidget_PcbCaseInfor.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Lower Case"))
        item = self.tableWidget_PcbCaseInfor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Width(mm)"))
        item = self.tableWidget_PcbCaseInfor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Depth(mm)"))
        item = self.tableWidget_PcbCaseInfor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Height(mm)"))
        item = self.tableWidget_PcbCaseInfor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Inner Thickness(mm)"))
        item = self.tableWidget_PcbCaseInfor.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Heatsink"))
        item = self.tableWidget_PcbCaseInfor.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Material"))
        __sortingEnabled = self.tableWidget_PcbCaseInfor.isSortingEnabled()
        self.tableWidget_PcbCaseInfor.setSortingEnabled(False)
        self.tableWidget_PcbCaseInfor.setSortingEnabled(__sortingEnabled)
        self.label_AmbientTemp.setText(_translate("MainWindow", "Ambient Temperature"))
        self.label_AmbientTempUnit.setText(_translate("MainWindow", "<html><head/><body><p>℃</p></body></html>"))
        self.label_ModelName.setText(_translate("MainWindow", "Model Name"))
        self.label.setText(_translate("MainWindow", "* Coated : Anodizing, Spray, Paint 처리 "))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/image/Tab1.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/image/Tab1-2.png\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_PCB), _translate("MainWindow", "Ambient Temp. and Geometry"))
        item = self.tableWidget_PcbLayers.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Layer 1 [TOP]"))
        item = self.tableWidget_PcbLayers.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Layer 2 [BOT]"))
        item = self.tableWidget_PcbLayers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Layer Thickness(mm)"))
        item = self.tableWidget_PcbLayers.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Copper Percentage(%)"))
        self.label_PcbLayerNumber.setText(_translate("MainWindow", "PCB Layer Number :"))
        self.pushButton_PcbLayerNumber.setText(_translate("MainWindow", "Apply"))
        self.Image_Stackup.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/image/Tab2.png\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Layers), _translate("MainWindow", "PCB Layer"))
        item = self.tableWidget_Components.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "IC 1"))
        item = self.tableWidget_Components.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "이름"))
        item = self.tableWidget_Components.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "실장위치"))
        item = self.tableWidget_Components.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "소자중심\n"
"X (mm)"))
        item = self.tableWidget_Components.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "소자중심\n"
"Z (mm)"))
        item = self.tableWidget_Components.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Width\n"
"(mm)"))
        item = self.tableWidget_Components.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Depth\n"
"(mm)"))
        item = self.tableWidget_Components.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Heigh\n"
"(mm)"))
        item = self.tableWidget_Components.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "기구부\n"
"접촉"))
        item = self.tableWidget_Components.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "모델\n"
"타입"))
        item = self.tableWidget_Components.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "열저항 J-C \n"
"(C/W)"))
        item = self.tableWidget_Components.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "열저항 J-B\n"
"(C/W)"))
        item = self.tableWidget_Components.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "소모전력\n"
"(W)"))
        item = self.tableWidget_Components.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "최대허용\n"
"온도 (℃)"))
        self.label_ComponentsNumber.setText(_translate("MainWindow", "소자 개수 :"))
        self.label_CompoentsNumberUnit.setText(_translate("MainWindow", "개"))
        self.pushButton_ComponentsNumber.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Comp), _translate("MainWindow", "Components"))
        self.pushButton_LoadModel.setText(_translate("MainWindow", "LOAD"))
        self.pushButton_DeleteModel.setText(_translate("MainWindow", "DELETE"))
        self.pushButton_CheckModel.setText(_translate("MainWindow", "CHECK DESIGN"))
        self.label_SimulationResult.setText(_translate("MainWindow", "Simulation Results"))
        item = self.tableWidget_SimulationResults.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "이름"))
        item = self.tableWidget_SimulationResults.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "실장위치"))
        item = self.tableWidget_SimulationResults.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "기구부\n"
"접촉"))
        item = self.tableWidget_SimulationResults.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "모델 타입"))
        item = self.tableWidget_SimulationResults.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "소모전력\n"
"(W)"))
        item = self.tableWidget_SimulationResults.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "최대허용\n"
"온도(℃)"))
        item = self.tableWidget_SimulationResults.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Junction\n"
"온도(℃)"))
        item = self.tableWidget_SimulationResults.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "TOP\n"
"온도(℃)"))
        item = self.tableWidget_SimulationResults.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Bottom\n"
"온도(℃)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Results"))
        self.pushButton_NewModel.setText(_translate("MainWindow", "New Model"))
        self.pushButton_SaveModel.setText(_translate("MainWindow", "Save Model"))
        self.pushButton_RunSimulation.setText(_translate("MainWindow", "Run Simulation"))
        self.pushButton_Exit.setText(_translate("MainWindow", "Exit"))

import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

